[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "tiago-sew-retargeting"
version = "0.0.0"
requires-python = ">=3.11,<3.12"
dependencies = [
  "numpy",
  "scipy",
  "pandas",
  "matplotlib",
  "mujoco==3.1.6",
  "PyYAML",
]

[project.optional-dependencies]
test = ["pytest"]

[tool.setuptools.packages.find]
where = ["src"]
